"Изменения: Звуки":
  - "**/*.ogg"

"Изменения: C#":
  - "**/*.cs"

"Изменения: Конфиг":
  - "**/*.toml"
  - "**/*.config"
  - "*.json"
  - ".github/*.yml"
  - ".github/*.json"
  - ".vscode/*.json"
  - ".editorconfig"

"Изменения: Документация":
  - "**/*.xml"
  - "**/*.md"

"Изменения: Локализация":
- 'Resources/Locale/**/*.ftl'

"Изменения: Карта":
  - "Resources/Maps/**/*.yml"
  - "Resources/Prototypes/Maps/**/*.yml"

"Изменения: Спрайт":
  - "**/*.rsi/*.png"
  - "**/*.rsi/*.json"

"Изменения: Интерфейс":
  - "**/*.xaml*"

"Изменения: YML":
  - any: ["**/*.yml"]
    all: ["!Resources/Maps/**/*.yml", "!Resources/Prototypes/Maps/**/*.yml"]

"Изменения: Github":
  - ".github/workflows/*.yml"

"СВЯТЫЕ УГОДНИКИ":
- "Content.Server.Database/*"
